# params.yaml
base: # Общие параметры, например, для воспроизводимости
  random_state: 42 # Фиксируем "зерно" для повторяемости результатов
  test_size: 0.2    # Доля тестовой выборки (20%)

prepare: # Параметры для стадии 'prepare' (src/prepare.py)
  target_col: "target" # Название целевой переменной в Iris (для нашего датасета)

train: # Параметры для стадии 'train' (src/train.py)
  model_type: "LogisticRegression" # Тип модели (для логирования в MLflow)
  solver: "liblinear"               # Алгоритм оптимизации для LogisticRegression
  max_iter: 1000                    # Максимальное количество итераций